<?php
/*
	IF YOU USE 'final' KEYWORD INFRONT OF ANY  CLASS
	OF METHOD, THIS WON'T BE EXTENDED (FOR CLASS) AND
	THIS CAN'T BE OVERRIDDEN (FOR METHOD) , 
	IF YOU TRY TO EXTEND OR USE IT'LL SHOW FATAL ERROR
*/

?>

